name: Publish to Github packages

on:
  push:
    tags: v*.*.*

  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com/gravitybv"

      - name: Install Dependencies
        run: |
          echo "@gravitybv:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=$PERSONAL_TOKEN" >> .npmrc
          npm install
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Publish package to github packages
        run: npm publish --access public --@gravitybv:registry=https://npm.pkg.github.com/gravitybv
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
