name: Publish to NPM

on:
  push:
    tags: v*.*.*

  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install npm dependencies
        run: npm install

      - name: Publish package to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish package to github packages
        run: npm publish --access public --@gravitybv:registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
